//@version=5
indicator("Bollinger Bands", overlay=true)

length = input(20, "Bollinger Bands Length")
mult = input(2.0, "Bollinger Bands Standard Deviation")

basis = ta.sma(close, length)
dev = mult * ta.stdev(close, length)

upperBand = basis + dev
lowerBand = basis - dev

plot(basis, color=color.blue, title="Basis")
plot(upperBand, color=color.red, title="Upper Band")
plot(lowerBand, color=color.green, title="Lower Band")
