//@version=5
strategy("MomentumBreaker", overlay = false)

closing_price = close

period_1 = input.int(20, title = "First Period")
period_2 = input.int(40, title = "Second Period")
period_3 = input.int(80, title = "Third Period")
period_4 = input.int(160, title = "Fourth Period")

calculate_slope(a, b) =>
    (ta.linreg(a, b, 0) - ta.linreg(a, b, 0)[b]) / b

weight_1 = 1.2
weight_2 = 1.1
weight_3 = 0.9
weight_4 = 0.8

slope_1 = (calculate_slope(closing_price, period_1) + calculate_slope(closing_price, period_1 / 2)) / 2 * weight_1
slope_2 = (calculate_slope(closing_price, period_2) + calculate_slope(closing_price, period_2 / 2)) / 2 * weight_2
slope_3 = (calculate_slope(closing_price, period_3) + calculate_slope(closing_price, period_3 / 2)) / 2 * weight_3
slope_4 = (calculate_slope(closing_price, period_4) + calculate_slope(closing_price, period_4 / 2)) / 2 * weight_4
combined_slope = (slope_1 + slope_2 + slope_4 + slope_4) / (weight_1 + weight_2 + weight_3 + weight_4) * 2

plot(slope_1, color = slope_1 > slope_1[1] ? color.green : color.red, linewidth = 1)
plot(slope_2, color = slope_2 > slope_2[1] ? color.green : color.red, linewidth = 2)
plot(slope_3, color = slope_3 > slope_3[1] ? color.green : color.red, linewidth = 3)
plot(slope_4, color = slope_4 > slope_4[1] ? color.green : color.red, linewidth = 4)
plot(combined_slope, color = combined_slope > combined_slope[1] ? color.blue : color.purple, linewidth = 4)

strategy.entry("BuySignal", strategy.long, qty = 10, when = combined_slope > combined_slope[1])
strategy.entry("SellSignal", strategy.short, qty = 1, when = combined_slope < combined_slope[1])
